apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: node-feature-discovery
resources:
- daemonset.yaml
- deployment.yaml
- rbac.yaml
- service.yaml
#configMapGenerator:
#- name: nfd-worker-conf
#  files:
#  - nfd-worker.conf
